export const data = [
  {
    id: "us",
    region: "USA",
    unitSpeedLong: "Miles per hour",
    unitSpeedShort: "mph",
    unitDistance: "Miles",
    unitVolume: "gallons",
    currency: "dollars",
    currencyicon: "./dollar.png",
    image: "./usa.jpg",
    timeZone: {
      long: "Eastern Daylight Time",
      short: "EST",
    },
    coordinates: [47.116386, -101.299591],
  },
  {
    id: "in",
    region: "India",
    unitSpeedLong: "kilometers per hour",
    unitSpeedShort: "kmph",
    unitDistance: "Kilometers",
    unitVolume: "Litres",
    currency: "rupees",
    currencyicon: "./rupee.png",
    image: "./india.jpg",
    timeZone: {
      long: "India Standard Time",
      short: "IST",
    },
    coordinates: [20.593684, 78.96288],
  },
  {
    id: "uk",
    region: "UK",
    unitSpeedLong: "Miles per hour",
    unitSpeedShort: "mph",
    unitDistance: "Miles",
    unitVolume: "gallons",
    currency: "pounds",
    currencyicon: "./pound.png",
    image: "./uk.jpg",
    timeZone: {
      long: "British Summer Time",
      short: "BST",
    },
    coordinates: [52.192001, -2.22],
  },
];
